# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conductor.ui'
#
# Created: Tue Jul  9 17:53:28 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Conductor(object):
    def setupUi(self, Conductor):
        Conductor.setObjectName(_fromUtf8("Conductor"))
        Conductor.resize(640, 520)
        self.bingresarConductor = QtGui.QPushButton(Conductor)
        self.bingresarConductor.setGeometry(QtCore.QRect(350, 310, 161, 31))
        self.bingresarConductor.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Descargas/IMAGENES/Ingresar.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bingresarConductor.setIcon(icon)
        self.bingresarConductor.setIconSize(QtCore.QSize(600, 360))
        self.bingresarConductor.setObjectName(_fromUtf8("bingresarConductor"))
        self.lEstSalida = QtGui.QLabel(Conductor)
        self.lEstSalida.setGeometry(QtCore.QRect(140, 190, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lEstSalida.setFont(font)
        self.lEstSalida.setObjectName(_fromUtf8("lEstSalida"))
        self.lIDConductor = QtGui.QLabel(Conductor)
        self.lIDConductor.setGeometry(QtCore.QRect(160, 100, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lIDConductor.setFont(font)
        self.lIDConductor.setObjectName(_fromUtf8("lIDConductor"))
        self.timeEditHoraLlegada = QtGui.QTimeEdit(Conductor)
        self.timeEditHoraLlegada.setGeometry(QtCore.QRect(490, 270, 118, 27))
        self.timeEditHoraLlegada.setObjectName(_fromUtf8("timeEditHoraLlegada"))
        self.lNPasajeros = QtGui.QLabel(Conductor)
        self.lNPasajeros.setGeometry(QtCore.QRect(170, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lNPasajeros.setFont(font)
        self.lNPasajeros.setObjectName(_fromUtf8("lNPasajeros"))
        self.dateEditFecha = QtGui.QDateEdit(Conductor)
        self.dateEditFecha.setGeometry(QtCore.QRect(110, 60, 171, 27))
        self.dateEditFecha.setObjectName(_fromUtf8("dateEditFecha"))
        self.bRegresarConductor = QtGui.QPushButton(Conductor)
        self.bRegresarConductor.setGeometry(QtCore.QRect(130, 310, 161, 31))
        self.bRegresarConductor.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Descargas/IMAGENES/Regresar.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRegresarConductor.setIcon(icon1)
        self.bRegresarConductor.setIconSize(QtCore.QSize(500, 1000))
        self.bRegresarConductor.setObjectName(_fromUtf8("bRegresarConductor"))
        self.timeEditHoraSalida = QtGui.QTimeEdit(Conductor)
        self.timeEditHoraSalida.setGeometry(QtCore.QRect(170, 270, 118, 27))
        self.timeEditHoraSalida.setObjectName(_fromUtf8("timeEditHoraSalida"))
        self.lNUnidad = QtGui.QLabel(Conductor)
        self.lNUnidad.setGeometry(QtCore.QRect(200, 130, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lNUnidad.setFont(font)
        self.lNUnidad.setObjectName(_fromUtf8("lNUnidad"))
        self.lineEEstacionSalida = QtGui.QLineEdit(Conductor)
        self.lineEEstacionSalida.setGeometry(QtCore.QRect(320, 190, 281, 21))
        self.lineEEstacionSalida.setObjectName(_fromUtf8("lineEEstacionSalida"))
        self.lEstLLegada = QtGui.QLabel(Conductor)
        self.lEstLLegada.setGeometry(QtCore.QRect(120, 220, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lEstLLegada.setFont(font)
        self.lEstLLegada.setObjectName(_fromUtf8("lEstLLegada"))
        self.lHoraSalida = QtGui.QLabel(Conductor)
        self.lHoraSalida.setGeometry(QtCore.QRect(30, 270, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lHoraSalida.setFont(font)
        self.lHoraSalida.setObjectName(_fromUtf8("lHoraSalida"))
        self.lHoraLLegada = QtGui.QLabel(Conductor)
        self.lHoraLLegada.setGeometry(QtCore.QRect(330, 270, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lHoraLLegada.setFont(font)
        self.lHoraLLegada.setObjectName(_fromUtf8("lHoraLLegada"))
        self.lineEEstLlegada = QtGui.QLineEdit(Conductor)
        self.lineEEstLlegada.setGeometry(QtCore.QRect(320, 220, 281, 21))
        self.lineEEstLlegada.setObjectName(_fromUtf8("lineEEstLlegada"))
        self.lFecha = QtGui.QLabel(Conductor)
        self.lFecha.setGeometry(QtCore.QRect(30, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lFecha.setFont(font)
        self.lFecha.setObjectName(_fromUtf8("lFecha"))
        self.lineENPasajeros = QtGui.QLineEdit(Conductor)
        self.lineENPasajeros.setGeometry(QtCore.QRect(320, 160, 281, 21))
        self.lineENPasajeros.setObjectName(_fromUtf8("lineENPasajeros"))
        self.titleConductores = QtGui.QLabel(Conductor)
        self.titleConductores.setGeometry(QtCore.QRect(220, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titleConductores.setFont(font)
        self.titleConductores.setObjectName(_fromUtf8("titleConductores"))
        self.lineENUnidad = QtGui.QLineEdit(Conductor)
        self.lineENUnidad.setGeometry(QtCore.QRect(320, 130, 281, 21))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineENUnidad.setFont(font)
        self.lineENUnidad.setObjectName(_fromUtf8("lineENUnidad"))
        self.lineEIDConductor = QtGui.QLineEdit(Conductor)
        self.lineEIDConductor.setGeometry(QtCore.QRect(320, 100, 281, 21))
        self.lineEIDConductor.setObjectName(_fromUtf8("lineEIDConductor"))

        self.retranslateUi(Conductor)
        QtCore.QMetaObject.connectSlotsByName(Conductor)

    def retranslateUi(self, Conductor):
        Conductor.setWindowTitle(_translate("Conductor", "Form", None))
        self.lEstSalida.setText(_translate("Conductor", "ESTACION SALIDA", None))
        self.lIDConductor.setText(_translate("Conductor", "ID CONDUCTOR", None))
        self.lNPasajeros.setText(_translate("Conductor", "N° PASAJEROS", None))
        self.lNUnidad.setText(_translate("Conductor", "N° UNIDAD", None))
        self.lEstLLegada.setText(_translate("Conductor", "ESTACION LLEGADA", None))
        self.lHoraSalida.setText(_translate("Conductor", "HORA SALIDA", None))
        self.lHoraLLegada.setText(_translate("Conductor", "HORA LLEGADA", None))
        self.lFecha.setText(_translate("Conductor", "FECHA", None))
        self.titleConductores.setText(_translate("Conductor", "CONDUCTORES", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Conductor = QtGui.QWidget()
    ui = Ui_Conductor()
    ui.setupUi(Conductor)
    Conductor.show()
    sys.exit(app.exec_())

        